### ISSUE TITLE
Create a rough prototype of the profile page

### ISSUE THREAD

**Issue by GabrielPedroza** [upe-webdev-2/codeclash-frontend#18]

**Comment by Mikeatron-User** [comment]
Completed the leaderboard feature of the profile page. It takes in data and creates the leaderboard based off of it. All my code is in [my branch](https://github.com/upe-webdev-2/codeclash-frontend/tree/feature/profile-page-leaderboard). Leaderboard is current populated by mock data.
![image](https://user-images.githubusercontent.com/70152741/204115251-8c6b5493-57c5-4bd5-b994-0f206bd5b299.png)

**Comment by cheesecakeassassin** [comment]
![image](https://user-images.githubusercontent.com/7333111/204365309-0a49c368-eb10-4760-9755-5c064ddfe115.png)

The rough prototype is complete and has been successfully merged together inside the feature/profile-page-leaderboard branch. Many thanks to Michael for doing super well on the leaderboard
