### ISSUE TITLE
Learn the basics of Blender (To create a 3D model if necessary)

### ISSUE THREAD

**Issue by GabrielPedroza** [upe-webdev-2/codeclash-frontend#8]
Once the UI/UX Designers have designed a nice design to any parts of the site, find a model and build it. (Use as little vertex's and edge's as possible). It does not need to look realistic unless otherwise specified. You can use YouTube as a walkthrough for a similar modeling that you are building. Blender Guru is a good channel

**Comment by Mikeatron-User** [comment]
Completed Donut Tutorial from Blender Guru and made Donut
![donut_render_3](https://user-images.githubusercontent.com/70152741/197267633-30e58768-29d6-40ab-8a35-d511f82f7ff5.png)

**Comment by Mikeatron-User** [comment]
Made a first prototype for the laptop. Feedback Welcomed.
![laptop_render](https://user-images.githubusercontent.com/70152741/197278775-3e6458c0-01c5-46f9-a296-b5587cf40fe3.png)

**Comment by CHENY073** [comment]
https://my.spline.design/untitled-0481a2da442d762a367837c8f7d04c96/
Created the prototype of the laptop also using Spline

**Comment by Mikeatron-User** [comment]
**Iteration 2**
@CHENY073 and I made laptop better match the required aesthetics. Will iterate on this design further through the weekend. The model's file type now is .glb as requested.
![iteration2_render1](https://user-images.githubusercontent.com/70152741/198705406-a936ae31-1824-4bde-a04e-c9d1ed8ebe57.png)

Download Link:
https://fiudit-my.sharepoint.com/:u:/g/personal/mpena137_fiu_edu/EaFoq7zjRQpOi3XoKvliAm0BJST2XkvQs5lvL6-mybLgtA?e=tEhUWP

**Comment by Mikeatron-User** [comment]
**Iteration3**
Added lettering to the keys for the keyboard as requested. @CHENY073 is going to finish the rest of the missing keys.
![image](https://user-images.githubusercontent.com/70152741/198923324-5aa26448-89e2-41a4-a576-e2c09cf6bf46.png)

Download Link (Blender File):
https://fiudit-my.sharepoint.com/:u:/g/personal/mpena137_fiu_edu/ERRrUU-RGO9GuR6A1A4XXOkBDxqq167NhXC-WPfdZ0cwzw?e=JMazhG

Download Link (GLB File):
https://fiudit-my.sharepoint.com/:u:/g/personal/mpena137_fiu_edu/EeIw6u1cjHFDtAq08vS3T9UB9uXOh4rCJDZ_ljmGNaB8eA?e=gL4jhY

**Comment by CHENY073** [comment]
I adjusted the size of the letter and added the missing key.
![Keyboard](https://user-images.githubusercontent.com/99201199/199785710-e282d489-5713-4e23-bb73-5ac195de46b6.jpg)
GLB File:
https://fiudit-my.sharepoint.com/:u:/g/personal/cwu033_fiu_edu/Ed04udPe17RImUxE8YbGgkgBrEljCBvl1BIaQRzZ9kE0bg?e=GhqgMY

**Comment by GabrielPedroza** [comment]
Overall, it looks great!! I did see the letters on the laptop and seems to have z-fighting. I'm not entirely sure if that is from the view of the model but if 2 or more different objects are **exactly** in the same position, the model will have a hard time to determine which one would be on top. If this is confirmed, all you need to do is move all the letter ever so slightly up in respect to the z axis and it should fix the issue

**Comment by Mikeatron-User** [comment]
**Iteration 5**
Fixed a few different keys not having their text positioned correctly. Attempted to fix the arrow keys not appearing by repositioning them, but this did not work.
![image](https://user-images.githubusercontent.com/70152741/200188585-04baa948-f620-4311-a138-abe8c4928d56.png)
GLB File: https://fiudit-my.sharepoint.com/:u:/g/personal/mpena137_fiu_edu/Ec9obSFCk6hElzl5fYLDdKsBAG7AmY_fvjnkR5ruNGQ2vQ?e=KfQOUe

**Comment by Mikeatron-User** [comment]
**Iteration 7**
Made the text on the keys a texture instead of meshes.
![image](https://user-images.githubusercontent.com/70152741/201489711-a72ef6f9-cd51-4fbe-8826-4dc8bc9671cd.png)
GLB File: https://fiudit-my.sharepoint.com/:u:/g/personal/mpena137_fiu_edu/ETsi3M6LEpxGh4Yyu7r1ZcMBOQi1YmF4RyuBipkr3uWNyg?e=m8Rmjc

**Comment by Mikeatron-User** [comment]
**Iteration 9**
Fixed the color scheme to match what was requested. Replaced image on screen. Need to figure out how to make the border of the screen black, this used to be the case on the original model, but for some reason this has changed.
![image](https://user-images.githubusercontent.com/70152741/204020567-ad8e3c60-19e1-4100-8abc-f392ade2fd0c.png)
**GLB File:** https://fiudit-my.sharepoint.com/:u:/g/personal/mpena137_fiu_edu/EU1MpUdQLbxEuyVpihEUDiwBzuS9vEWnpx_u385zifFZ_Q?e=CVJQHy

**Comment by Mikeatron-User** [comment]
Iteration 10
Made border of screen black.
![image](https://user-images.githubusercontent.com/70152741/204023223-bf3d8976-086e-48f1-9d35-f534f103b8dd.png)
GLB File: https://fiudit-my.sharepoint.com/:u:/g/personal/mpena137_fiu_edu/EbbaIL3XQ2lNvf9ZxjQ_GicBdbW6byzyRahPA3qFZJx2nQ?e=dvOM8e
